apiVersion: apps/v1
kind: Deployment
metadata:
  name: docimage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docimage
  template:
    metadata:
      labels:
        app: docimage
    spec:
      containers:
      - name: docimage
        image: kalyanteja/demo:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: cal01
