apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosite-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demosite
  template:
    metadata:
      labels:
        app: demosite
    spec:
      containers:
      - name: demosite
        image: kalyanteja/demo:latest
        ports:
        - containerPort: 80
      imagepullsecrets:
      - name: cal01
