apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosite-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demosite
  template:
    metadata:
      labels:
        app: demosite
    spec:
      containers:
      - name: demosite
        image: demo-html:v1
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: demosite-service
spec:
  selector:
    app: demosite
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
  type: LoadBalancer
